#server.tomcat.uri-encoding=UTF-8
server:
  port: 9090
  tomcat.uri-encoding: UTF-8
  jsp:
    init-parameters:
      development: true

spring:
  profiles:
    active: prod
  servlet.multipart.max-file-size: 10MB
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  datasource:
    url: jdbc:mysql://db.runspeeds.com:3306/green_speed?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: mobplus
    password: mobplus-mysql-pwd.!
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=3000
#    # 此配置项会影响性能，只在排查的时候打开，系统运行时最好关闭。
#    removeAbandoned: true
#    removeAbandonedTimeout: 60
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hbm2ddl.auto: none
    show-sql: false
    open-in-view: true
  freemarker:
    suffix: .ftl #设定模板的后缀
    charset: UTF-8
    #    cache: false
    settings:
      classic_compatible: true
      tag_syntax: auto_detect
      number_format: 0.######
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
#      template_update_delay: 0

#验证码背景图张数
captcha.background.count: 10
captcha.background.pattern: /captcha/captcha_bg_%s.jpg

logging.level.web: info
